[package]
name = "wasm-pack-test"
version = "0.1.0"
authors = ["Sven Sauleau <sven@sauleau.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }